### ISSUE TITLE
Processing node_modules failed. Error: spawn EACCES

### ISSUE THREAD

**Issue by andrew19881123** [NativeScript/sample-android-background-services#1]
i cloned the git and i did

```
nmp install
tns run android
```

and i received the error: Processing node_modules failed. Error: spawn EACCES

i managed to get the app to build by removing and adding back the android platform

**Comment by keesvandieren** [comment]
Reason is gradlew has no executable flag.

chmod +x platform/android/gradlew

**Comment by robophil** [comment]
```bash
chmod +x platforms/android/gradlew.bat
```

just to be sure, add the `.bat` file extension, and platforms is missing an `s` @keesvandieren

**Comment by petekanev** [comment]
Project got a much needed clean-up and this should no longer be an issue.

**Comment by bastianjoel** [comment]
I've got the same issue after updating Nativescript to the newest version on Ubuntu. 
In every project I'm starting I need to run `chmod +x platforms/android/gradlew` to get the builds running on android.
