### ISSUE TITLE
Full Angular 2 Example

### ISSUE THREAD

**Issue by sam0829** [NativeScript/sample-android-background-services#11]
Hello, please provide a full demo of this in Angular2. I am trying to implement this with my limited knowledge of Angular2. A proper demo will be very helpful.

I run this demo with TS & got run time exception that "NotificationIntentService" class not found.
So after searching a little, I am implementing based on the this issue : [https://github.com/NativeScript/sample-android-background-services/issues/6](url)

but then the project fails to compile saying "com" not found.

Do I need to use "declare module com" etc in d.ts file as well?

**Comment by petekanev** [comment]
The code should work in both TypeScript and JavaScript, since one is essentially the other, just sprinkled with some sugar and fancy warnings.

If you still wish to use TypeScript for the class, here's what it would look like:
```ts
// services/MyIntentService.ts 
declare var com: any; // this is the important bit if you wish for the TS transpiler to not complain

JavaClass("com.a.b.c.MyIntentService")
class MyIntentService extends com.pip3r4o.android.app.IntentService {

}
```

If you however still opt in for the JavaScript file, a class will still be generated, and you could still use it as any other Java class. If consumed in TS, you will still want to describe a proper namespace structure `declare module com { export module a { export module b { export module c { export class MyIntentService } } } }` for example so that TypeScript will recognize the new class additions in your code.

**Comment by sam0829** [comment]
Thanks for your quick reply, I am still not able to get this up running. What I tried is,
I created a hello world --ng app. then copied all the service / broadcast related js files from this demo. I used the js files from demo without changing a single line.

Then I initiated the service helper in `app.component.ts` like :
`var services =  require("./service-helper");`
`services.setupAlarm(utils.ad.getApplicationContext());`

This sets & triggers the broadcast receiver `NotificationEventReceiver`

But after that app crashes while starting the service saying
`TypeError: Cannot read property 'NotificationIntentService' of undefined`

The line where it crashes is 
`var intent = new Intent(context, com.tns.notifications.NotificationIntentService.class);`
inside the `NotificationEventReceiver`

I tried to change that line with :
`var intent = new Intent(context, java.lang.Class.forName("com.tns.notifications.NotificationIntentService.class"));`

With this change, app is crashing saying 
`java.lang.ClassNotFoundException: com.tns.notifications.NotificationIntentService`

I then tried to create NotificationIntentService.d.ts with following code
```
declare module com {
    export module tns {
        export module notifications {
            export class NotificationIntentService { }
        }
    }
}
```

but still app is crashing. Am I missing something?

Service is defined in AndroidManifest as well like this :
`<service  android:name="com.tns.notifications.NotificationIntentService"
            android:enabled="true"
            android:exported="false" />
`

**Comment by petekanev** [comment]
Only thing I can think of is that you don't have the additional utilities package which aims to patch the lack of a constructor with no parameters for the android IntentService. 

https://github.com/NativeScript/sample-android-background-services/blob/master/app/notifications/NotificationIntentService.js#L1

`npm install nativescript-android-utils --save` 
https://github.com/NativeScript/sample-android-background-services/blob/master/package.json#L13

It's a minimalistic implementation of the android class that can be safely extended. The source code is available online if security is a concern.

**Comment by sam0829** [comment]
Thanks @Pip3r4o . installing nativescript-android-utils solved the issue.

**Comment by vswee** [comment]
@Pip3r4o You are a gem. It's working swimmingly now!

**Comment by sadiqna** [comment]
@sam0829, @Pip3r4o , @vswee  , can you provide working sample solution for android background services with nativescript angular.

**Comment by petekanev** [comment]
@sadiqna there is no difference in how you would consume android background services between NativeScript Angular and NativeScript with TypeScript/JavaScript
