### ISSUE TITLE
Use background service without alarm

### ISSUE THREAD

**Issue by mrTR24** [NativeScript/sample-android-background-services#12]
How can i use this background service without the alarm service triggering every 5 min .I want to run bluetooth in this background service so as to keep the BLE connection through out the application.
Thanks

function setupAlarm(context,notificationEventReceiver) {
    getStartPendingIntent(context);
}

i am just call the getStartPendingIntent() function in setupAlarm but its not calling the tns.broadcastreceivers.NotificationEventReceiver.class. 

Anything am missing?Thanks

**Comment by petekanev** [comment]
Hey @mrTR24.

Please understand that this is just one of a hundred use-cases for background services android. You can implement your own as you see fit.

A quick google search yielded a lot of results for your particular case. Here's one of them:
http://stackoverflow.com/a/36678147/6408287

**Comment by mrTR24** [comment]
thanks for replying me @Pip3r4o 

for android(native) : have used this http://stackoverflow.com/questions/25267753/how-to-keep-bluetooth-connection-in-background

and it worked 

am new to Nativescript . this background service example is the best that i have found.am not being able to find a proper bg service example for bluetooth in nativescript. 

any suggestion or advise?

**Comment by petekanev** [comment]
Unless something has been made into a nativescript plugin already, you would have to implement functionalities yourself either in JavaScript (as done in this sample) or in Java code and then invoked through your JavaScript code.

**Comment by mrTR24** [comment]
thank you for the reply
