### ISSUE TITLE
The sample don't run on nativescript version 3.0.1

### ISSUE THREAD

**Issue by juanitozambada** [NativeScript/sample-android-background-services#13]
Everything is Ok when you download and run the sample, but I try to reproduce the sample with nativescript 3.0.1 and ... Don't run

I need background services for {N} 3.0.1

Can you help us?

**Comment by petekanev** [comment]
Hey @juanitozambada I can't help you without you telling me what you've tried so far, the environment the sample runs on, any related code or code you consider to be relevant to the case. Any visible errors or logs. 

The sample is version-agnostic so it shouldn't matter if you run this on 2.3, 2.5, or 3.0

**Comment by juanitozambada** [comment]
I did the following:

    git clone https://github.com/NativeScript/sample-android-background-services
    cd sample-android-background-services

then, I upgrade:

   tns update next

then i got the following in package.json file

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.bgservice",
    "tns-android": {
      "version": "3.1.0-next-2017-06-07-1854"
    }
  },
  "dependencies": {
    "nativescript-android-utils": "^1.0.2",
    "tns-core-modules": "^3.1.0-2017-06-08-6861"
  },
  "devDependencies": {
    "babel-traverse": "6.12.0",
    "babel-types": "6.11.1",
    "babylon": "6.8.4",
    "lazy": "1.0.11",
    "nativescript": "^2.4.2"
  }
}

but, when I:     tns run android
I got the following:

:compileF1F2DebugJavaWithJavac
C:\nativescript\s2\sample-android-background-services\platforms\android\src\main\java\com\tns\broadcastreceivers\NotificationEventReceiver.java:4: error: NotificationEventReceiver is not abstract and does not override abstract method onReceive(Context,Intent) in BroadcastReceiver
public class NotificationEventReceiver extends android.support.v4.content.WakefulBroadcastReceiver implements com.tns.NativeScriptHashCodeProvider {
       ^
C:\nativescript\s2\sample-android-background-services\platforms\android\src\main\java\com\tns\notifications\NotificationIntentService.java:4: error: NotificationIntentService is not abstract and does not override abstract method onHandleIntent(Intent) in IntentService
public class NotificationIntentService extends com.pip3r4o.android.app.IntentService implements com.tns.NativeScriptHashCodeProvider {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
:compileF1F2DebugJavaWithJavac FAILED

**Comment by petekanev** [comment]
@juanitozambada I'll have a look and let you know when I've got updates.

**Comment by petekanev** [comment]
@juanitozambada I've since isolated the problem in the android runtime, a fix will be available with the @next build some time next week, or immediately with the 3.1 release.

**Comment by juanitozambada** [comment]
Thanks a lot. I appreciate your effort!

**Comment by petekanev** [comment]
@surdu @juanitozambada I pushed a fix to the android runtime. Feel free to test it away by first installing the latest bits from master: `tns platform add android@next`.

**Comment by juanitozambada** [comment]
You´re amazing!, thanks a lot.
