### ISSUE TITLE
crash android version 4.4.4

### ISSUE THREAD

**Issue by MJ-Vakili** [NativeScript/sample-android-background-services#14]
crash android version 4.4.4

error msg:
`An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onHandleIntent failed

Error: java.lang.NoSuchMethodError: no method with name='setColor' signature='(I)Landroid/app/Notification$Builder;' in class Landroid/app/Notification$Builder;
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.access$2400(Runtime.java:33)
    com.tns.Runtime$3.run(Runtime.java:1033)
    android.os.Handler.handleCallback(Handler.java:733)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:136)
    android.app.ActivityThread.main(ActivityThread.java:5001)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    dalvik.system.NativeStart.main(Native Method)
File: "/data/data/org.nativescript.bgservice/files/app/notificati`

**Comment by petekanev** [comment]
Thank you for reporting the problem! You can adjust the demo inside https://github.com/NativeScript/sample-android-background-services/blob/master/app/notifications/NotificationIntentService.js to not call methods unavailable in API 19.

**Comment by NickIliev** [comment]
CLosing as the updated demo is meant to work only on API26 and above
