### ISSUE TITLE
 Documentation for javascript

### ISSUE THREAD

**Issue by nrbn** [NativeScript/sample-android-background-services#16]
I need guidance in just javascript version. My application is only on javascript and this plugin is only available with typescript and angular. 

A proper demo of javascript will be very helpful. Can you help me please?

**Comment by petekanev** [comment]
@nrbn that is incorrect - the demo is purely in JavaScript, and the code can be straight out copy-pasted inside a TypeScript (angular) app and it will still work. 

Please read the blog post on android background services in NativeScript.
