### ISSUE TITLE
Requires nativescript-android-utils

### ISSUE THREAD

**Issue by SteveOliverC** [NativeScript/sample-android-background-services#17]
You need to include this plugin in your own projects so that the NotificationIntentService can be found. I missed this step if it was in the instructions.

https://github.com/Pip3r4o/nativescript-android-utils

**Comment by petekanev** [comment]
The project demo already references the nativescript-android-utils as can be seen in the package.json - https://github.com/NativeScript/sample-android-background-services/blob/master/package.json
