### ISSUE TITLE
Can not access typescript class from service

### ISSUE THREAD

**Issue by DivyeshSharma** [NativeScript/sample-android-background-services#20]
I build my nativescript app(Nativescript verison 3.1.2) in which i want to call REST API and store result of it in database when app is in foreground or background, so i used android Service to make it possible to run my app in background. My Service working nice but i want to access typescript class here to call api but i am not able to do that as there is nothing like constructor here so i can't inject instance of my api_service class and can not call method of that class.

Here is my code Snippets:

Serivce Class:
```typescript
import { RestCallService } from "../common/restcall.service";
import { AuthenticationService } from "../authentication.service";
import { Http, ConnectionBackend, RequestOptions } from "@angular/http";

declare let android: any;
declare let com: any;
var _timerId;
var Toast = android.widget.Toast;
var utils = require("utils/utils");
var _backend: ConnectionBackend;
var _defaultOptions: RequestOptions;
let http = new Http(_backend, _defaultOptions);
let authenticationService = new AuthenticationService(http);

com.pip3r4o.android.app.IntentService.extend("com.tns.pages.service.myService", {
    onStartCommand: function (intent, flags, startId) {
        console.log("Inside onStartCommand()");
        _timerId = setInterval(function () {
            callApiAndStoreData();
            console.log("Hello !!");
            Toast.makeText(utils.ad.getApplicationContext(), "Toast after timeout from Service", Toast.LENGTH_SHORT).show();
        }, 5000);

        return android.app.Service.START_STICKY;
    },
    onDestroy: function () {
        clearTimeout(_timerId);
        console.log("onDestroy() is called");
    },
    onHandleIntent: function (intent) {
        console.log("Inside onHandleIntent()");
    }
});


function callApiAndStoreData() {
    console.log("callApiAndStoreData() is called...");
    try {
        authenticationService.getSession().subscribe(response => {
            console.log("RESPONSE => " + response);
        }, (error) => {
            console.log("Error getSession()" + error);
        });
    } catch (error) {
        console.log("ERROR => " + error);
    }
}
```

Authentication Serivce class (API call):
```typescript
import { Injectable, } from '@angular/core';
import { Http, Headers, Response } from "@angular/http";
import { Observable } from "rxjs/Rx";
import "rxjs/add/operator/map";
import "rxjs/add/operator/catch";
import { environment } from '../environments';
/**
 * Service class which will handle Authentication related API calls & might have
 * some helper methods for API calls.
 */
@Injectable()
export class AuthenticationService {
    public changePhoneValue: any = {};

    constructor(public _http: Http) {
    }

    handleErrors(error: Response) {
        console.error("Error => " + error.json());
        return Observable.throw(error);
    }

    public getSession(): Observable<any> {
        try {     
            	return this._http.get(`${environment.origin}auth/session` // api call it gave me error and catch block gave me error
            ).map((response: Response) => response)
                .catch(this.handleErrors);
        }catch(error){
            console.log("ERROR => "+error);
        } 
    }
}
```
I got below error in catch block:
JS: ERROR => TypeError: Cannot read property 'merge' of undefined
JS: ERROR => TypeError: Cannot read property 'subscribe' of undefined

So How Can i able to call my authenicaton service class and make it possible to call api and store data in database. Is it possible to access typescript class from andropid service.Can anyone please help here, its urgent!
Please reply if anyone has any solution.

**Comment by petekanev** [comment]
I am not sure where `merge` is coming from, also AFAIK subscribe is used to resolve promises. Make sure that that whatever you call `subscribe` on is not undefined. The code in this repository is not special in any way, in the sense that you still write TypeScript/JavaScript and still have access to all your project files and scripts.

**Comment by DivyeshSharma** [comment]
how can i able to inject instance of my typescript class in that service class without constructor is there any way cause the main issue here is object/instance is not created properly. So is there any alternative to inject instance without injecting it in constructor.

**Comment by ekta159** [comment]
Thanks for you reply  Yes, you are right, this is happening because I am creating parameters expected by API service manually.
I am doing this because my android service is defined in another file “MyAndroidService.js”, and that’s why I need instance of APIService.
ts in MyAndroidService.js for calling API. I am not sure how can I create new instance of it inside as normally we inject the service in constructor of component. but as “MyAndroidService” is not an component, I can’t declare constructor & hence I am not getting the instance of APIService in it. So how can I achieve this?

APIService.ts

import { Injectable, } from '@angular/core';
import { Http, Headers, Response } from "@angular/http";
import { Observable } from "rxjs/Rx";
import "rxjs/add/operator/map";
import "rxjs/add/operator/catch";
import { environment } from '../environments';
/**
 * Service class which will handle Authentication related API calls & might have
 * some helper methods for API calls.
 */
@Injectable()
export class APIService {
    public changePhoneValue: any = {};

    constructor(public _http: Http) {
    }

    handleErrors(error: Response) {
        console.error("Error => " + error.json());
        return Observable.throw(error);
    }

    public getSession(): Observable<any> {
        try {     
            	return this._http.get(`${environment.origin}auth/session` // api call it gave me error and catch block gave me error
            ).map((response: Response) => response)
                .catch(this.handleErrors);
        }catch(error){
            console.log("ERROR => "+error);
        } 
    }
}


MyAndroidService.ts

import { RestCallService } from "../common/restcall.service";
import { APIService } from "../authentication.service";
import { Http, ConnectionBackend, RequestOptions } from "@angular/http";

declare let android: any;
declare let com: any;
var _timerId;
var Toast = android.widget.Toast;
var utils = require("utils/utils");
var _backend: ConnectionBackend;
var _defaultOptions: RequestOptions;
let http = new Http(_backend, _defaultOptions);
let apiService = new APIService(http);

com.pip3r4o.android.app.IntentService.extend("com.tns.pages.service.MyAndroidService", {
    onStartCommand: function (intent, flags, startId) {
        console.log("Inside onStartCommand()");
        _timerId = setInterval(function () {
            callApiAndStoreData();
            console.log("Hello !!");
            Toast.makeText(utils.ad.getApplicationContext(), "Toast after timeout from Service", Toast.LENGTH_SHORT).show();
        }, 5000);

        return android.app.Service.START_STICKY;
    },
    onDestroy: function () {
        clearTimeout(_timerId);
        console.log("onDestroy() is called");
    },
    onHandleIntent: function (intent) {
        console.log("Inside onHandleIntent()");
    }
});


function callApiAndStoreData() {
    console.log("callApiAndStoreData() is called...");
    try {
        apiService.getSession().subscribe(response => {
            console.log("RESPONSE => " + response);
        }, (error) => {
            console.log("Error getSession()" + error);
        });
    } catch (error) {
        console.log("ERROR => " + error);
    }
}

**Comment by petekanev** [comment]
At this point I am not sure if you can "inject" the service in that sense. You could provide an implementation when extending the class by defining an `init: function() { ctor code executed here }` in your class implementation, but I am not sure whether that would work with javascript dependency injection.

**Comment by arslanyasin** [comment]
Hi DivyeshSharma and pip3r4o
i am trying to use service in my app but can't do i am new on nativescript with angular can you please guide how can i use service and call its start command as you give 2 of yours classes.

Thank you.

**Comment by petekanev** [comment]
@ArslanYasin I am not sure what you are asking exactly. There is a blog post on the matter, and a lot of resources online on how to work with Services in android. 

https://www.nativescript.org/blog/using-android-background-services-in-nativescript

**Comment by arslanyasin** [comment]
@DivyeshSharma @Pip3r4o  i have same issue could not understand this problem getting same error 
"merge" of undefined please help me... thanks
