### ISSUE TITLE
Im Not able to use the patch  com.pip3r4o.android.app.IntentService.extend is undefined

### ISSUE THREAD

**Issue by cesarvega** [NativeScript/sample-android-background-services#24]
Hi guys I got this application in typescript running I will post my code at the end for you just to paste and run , so far all is working until the part that I get an error saying I need to do an empty constructor when I implement the code below

PLEASE ANY HELP to figure how to make the patch works is the only piece missing for 
   **"nativescript-android-utils": "^1.0.2",**
 **"tns-core-modules": "^3.4.0",**
I sue this code first 
```
android.app.IntentService.extend("com.tns.notifications.NotificationIntentService" , {
            onHandleIntent: function (intent) {                              
         });
```

But then I use this code instead because it suppose to have a patch for the empty constructor but when I debug 
is tellin me  that com.pip3r4o.android.app = _undefined_

```
 com.pip3r4o.android.app.IntentService.extend("com.tns.notifications.NotificationIntentService", {
            onHandleIntent: function (intent) {
         });
```

Here is my dependencies whit the important ones balded

 "dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "font-awesome": "^4.7.0",
    **"nativescript-android-utils": "^1.0.2",**
    "nativescript-angular": "~4.4.0",
    "nativescript-camera": "^3.1.4",
    "nativescript-cardview": "^2.0.4",
    "nativescript-drop-down": "^3.2.0",
    "nativescript-emoji": "^1.1.1",
    "nativescript-geolocation": "^4.2.0",
    "nativescript-google-maps-sdk": "^2.4.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-telephony": "^1.0.4",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.6",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    **"tns-core-modules": "^3.4.0",**
    "url-search-params-polyfill": "^2.0.1",
    "zone.js": "~0.8.2"
  },

here is the code in one file no need separate files just paste this in a service and call it from any component and you will see for yourself where is breaking, 

POSSIBLE SOLUTION might be making com.pip3r4o.android.app work with the latest tns-core-modules": "^3.4.0 but i dont know how 

`  testService() {

        com.pip3r4o.android.app.IntentService.extend("com.tns.notifications.NotificationIntentService" /* give your class a valid name as it will need to be declared in the AndroidManifest later */, {
            onHandleIntent: function (intent) {
                
                var action = intent.getAction();
                if ("ACTION_START" == action) {
                    postNotification();
                } else if ('ACTION_STOP' == action) {
                 /* get the system alarm manager and cancel all pending alarms, which will stop the service from executing periodically  */
                }
                android.support.v4.content.WakefulBroadcastReceiver.completeWakefulIntent(intent);  
            }           
         });

         function postNotification() {
            // Do something. For example, fetch fresh data from backend to create a rich notification?
            var utils = require("utils/utils");
            var context = utils.ad.getApplicationContext(); // get a reference to the application context in Android
            var builder = new android.app.Notification.Builder(context);
            builder.setContentTitle("Scheduled Notification")
                .setAutoCancel(true)
                .setColor(android.R.color.holo_purple) // optional
                .setContentText("This notification has been triggered by Notification Service")
                .setVibrate([100, 200, 100]) // optional
                .setSmallIcon(android.R.drawable.btn_star_big_on);
                // will open main NativeScript activity when the notification is pressed
            var mainIntent = new android.content.Intent(context, com.tns.NativeScriptActivity.class);
            var pendingIntent = android.app.PendingIntent.getActivity(context,
                1,
                mainIntent,
                android.app.PendingIntent.FLAG_UPDATE_CURRENT);
            builder.setContentIntent(pendingIntent);
            builder.setDeleteIntent(getDeleteIntent(context));
            var manager = context.getSystemService(android.content.Context.NOTIFICATION_SERVICE);
            manager.notify(1, builder.build());
         }

         /* only necessary for dismissing the notification from the Notifications Screen */
         function getDeleteIntent(context) {
                var intent = new android.content.Intent(context, com.tns.broadcastreceivers.NotificationEventReceiver.class);
                intent.setAction("ACTION_DELETE_NOTIFICATION");
                return android.app.PendingIntent.getBroadcast(context, 0, intent, android.app.PendingIntent.FLAG_UPDATE_CURRENT);
         }
       
        //BROADCASTER
     
         
         android.support.v4.content.WakefulBroadcastReceiver.extend("com.tns.broadcastreceivers.NotificationEventReceiver", {       
            onReceive: function(context, intent){
                var action = intent.getAction();
                var serviceIntent = null;
                if ("ACTION_START_NOTIFICATION_SERVICE" == action) {
                    console.log("onReceive from alarm, starting notification service! thread: ");
                    serviceIntent = createIntentStartNotificationService(context);
                } else if ("ACTION_DELETE_NOTIFICATION" == action) {
                    console.log("onReceive delete notification action, starting notification service to handle delete");
                    serviceIntent = createIntentDeleteNotification(context);
                }        
                if (serviceIntent) {
                    android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(context, serviceIntent);
                }
            }
         })

         var Intent = android.content.Intent;
         function createIntentStartNotificationService(context) {
            var intent = new Intent(context, com.tns.notifications.NotificationIntentService.class);
            intent.setAction("ACTION_START");
            return intent;
         }

         function createIntentDeleteNotification(context) {
            var intent = new Intent(context, com.tns.notifications.NotificationIntentService.class);
            intent.setAction("ACTION_DELETE");
            return intent;
         }

        // Set The Alarm and the intet to pass 

         function getStartPendingIntent(context) {
            var alarmIntent = new android.content.Intent(context, com.tns.broadcastreceivers.NotificationEventReceiver.class);
            alarmIntent.setAction("ACTION_START_NOTIFICATION_SERVICE");
            return android.app.PendingIntent.getBroadcast(context, 0, alarmIntent, android.app.PendingIntent.FLAG_UPDATE_CURRENT);
         }

         setupAlarm();// call setUpAlrm to beging the Intent 
         function setupAlarm() {
            var utils = require("utils/utils");
            var context = utils.ad.getApplicationContext();
            var alarmManager = context.getSystemService(android.content.Context.ALARM_SERVICE);
            var alarmIntent = getStartPendingIntent(context);
            var d = new Date();
            var currentTime = d.getTime();           

            alarmManager.setRepeating(android.app.AlarmManager.RTC_WAKEUP,          
                currentTime,
                1000  * 3, /* alarm will send the `alarmIntent` object every 3 seconds */
                alarmIntent);
         }
        
    };
`

**Comment by petekanev** [comment]
@cesarvega the `com.pip3r4o.android.app.IntentService` class was made for the sole purpose of circumventing the `error saying I need to do an empty constructor`. 

The IntentService IS undefined, unless you install the `nativescript-android-utils` package, which is where the custom IntentService comes from!
