### ISSUE TITLE
Nativescript Angular example

### ISSUE THREAD

**Issue by ghost** [NativeScript/sample-android-background-services#27]
I really don't have a single idea how to implement it using nativescript-angular template.

**Comment by NickIliev** [comment]
@jannotabamo the workflow is exactly the same - you need to follow the steps described in the README.
I've also added Webpack to the demo to show the steps needed to bundle an application with extended classes.

**Comment by juniorschen** [comment]
@NickIliev Incredible time that I am spending finding several people with the same doubts and having problems using it with angular and seeing this wonderful answer
