### ISSUE TITLE
Error on the NativeScript/sample-android-background-services

### ISSUE THREAD

**Issue by SathyaVS** [NativeScript/sample-android-background-services#32]
Hi,
I am getting the below issue while run the given sample app, i am using API 26 emulator please help me to rectify these errors.

Successfully synced application org.nativescript.bgservice on device 192.168.67.102:5555.
JS: Job Scheduled: 1
JS: Job execution ...
10-08 11:33:49.257  2600  2600 E AndroidRuntime:        at com.tns.Runtime.callJSMethodNative(Native Method)
10-08 11:33:49.257  2600  2600 E AndroidRuntime:        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-08 11:33:49.257  2600  2600 E AndroidRuntime:        at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-08 11:33:49.257  2600  2600 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-08 11:33:49.257  2600  2600 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-08 11:33:49.257  2600  2600 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: java.lang.RuntimeException: com.tns.NativeScriptException:
System.err: Calling js method onStartJob failed
System.err:
System.err: TypeError: android.app.NotificationChannel is not a constructor
System.err: File: "file:///data/data/org.nativescript.bgservice/files/app/notifications/MyJobService.js, line: 29, column: 25
System.err:
System.err: StackTrace:
System.err:     Frame: function:'onStartJob', file:'file:///data/data/org.nativescript.bgservice/files/app/notifications/MyJobService.js', line: 29, column: 26
System.err:
System.err:     at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onStartJob failed
System.err:
System.err: TypeError: android.app.NotificationChannel is not a constructor
System.err: File: "file:///data/data/org.nativescript.bgservice/files/app/notifications/MyJobService.js, line: 29, column: 25
System.err:
System.err: StackTrace:
System.err:     Frame: function:'onStartJob', file:'file:///data/data/org.nativescript.bgservice/files/app/notifications/MyJobService.js', line: 29, column: 26
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.notifications.MyJobService.onStartJob(MyJobService.java:18)
System.err:     at android.app.job.JobService$1.onStartJob(JobService.java:71)
System.err:     at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
System.err:     ... 6 more

**Comment by SimonGuertin4** [comment]
I'm getting the same issue here.

**Comment by priyakathiresan1** [comment]
I'm also getting same issue here

**Comment by raulvc** [comment]
Background services did work before, some unrelated update must've broken it and I'm now getting these errors after successfully scheduling...

**Comment by NickIliev** [comment]
The project is now updated to NativeScript 5.x.x and the issue is not reporducible
