### ISSUE TITLE
Cannot read property `MyJobService`

### ISSUE THREAD

**Issue by klever34** [NativeScript/sample-android-background-services#35]
System.err: TypeError: Cannot read property 'MyJobService' of undefined
System.err: File: "file:///data/data/org.project.app/files/app/bundle.js, line: 485, column: 83
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'scheduleJob', file:'file:///data/data/org.project.app/files/app/bundle.js', line: 485, column: 84
System.err: 	Frame: function:'onTap', file:'file:///data/data/org.project.app/files/app/bundle.js', line: 119, column: 20
System.err: 	Frame: function:'invoker', file:'file:///data/data/org.project.app/files/app/vendor.js', line: 6565, column: 18
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.project.app/files/app/vendor.js', line: 20236, column: 15
System.err: 	Frame: function:'Observable._emit', file:'file:///data/data/org.project.app/files/app/vendor.js', line: 20264, column: 12
System.err: 	Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.project.app/files/app/vendor.js', line: 31793, column: 15
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err: 	at com.tns.gen.java.lang.Object_vendor_31783_26_ClickListenerImpl.onClick(Object_vendor_31783_26_ClickListenerImpl.java:17)
System.err: 	at android.view.View.performClick(View.java:6947)
System.err: 	at android.widget.TextView.performClick(TextView.java:12742)
System.err: 	at android.view.View$PerformClick.run(View.java:26313)
System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by NickIliev** [comment]
@klever34 the app is now migrated to NativeScript 5 and the issue should not manifest - please do let me know if you are still experiencing this one.
