### ISSUE TITLE
Application crashes on calling scheduleJob method

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/sample-android-background-services#41]
Reproduced with tns-core-modules@6.0.0 and android-runtime@6.0.0

1. Run application 
2. Click on button 
3. Application crashes with the following error:

--------- beginning of main
07-24 10:52:03.915  1269  1628 W audio_hw_generic: Not supplying enough data to HAL, expected position 1525688 , only wrote 1389422
07-24 10:52:06.037  3239  3239 I JS      : ComponentInfo{org.nativescript.bgservice/com.tns.notifications.MyJobService}
07-24 10:52:06.041  3239  3239 I JS      : Job Scheduled: 1
07-24 10:52:06.045  3239  3239 I JS      : Job execution ...
07-24 10:52:06.247  3239  3239 E JobService: Error while executing job: 1
07-24 10:52:06.247  3239  3239 D AndroidRuntime: Shutting down VM
07-24 10:52:06.248  3239  3239 W System.err: An uncaught Exception occurred on "main" thread.
07-24 10:52:06.248  3239  3239 W System.err: com.tns.NativeScriptException: Calling js method onStartJob failed
07-24 10:52:06.248  3239  3239 W System.err: Error: java.lang.NoSuchFieldError: no "I" field "IMPORTANCE_LOW" in class "Landroid/app/NotificationManager;" or its superclasses
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.notifications.MyJobService.onStartJob(MyJobService.java:21)
07-24 10:52:06.248  3239  3239 W System.err:     android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
07-24 10:52:06.248  3239  3239 W System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
07-24 10:52:06.248  3239  3239 W System.err:     android.os.Looper.loop(Looper.java:148)
07-24 10:52:06.248  3239  3239 W System.err:     android.app.ActivityThread.main(ActivityThread.java:5417)
07-24 10:52:06.248  3239  3239 W System.err:     java.lang.reflect.Method.invoke(Native Method)
07-24 10:52:06.248  3239  3239 W System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-24 10:52:06.248  3239  3239 W System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-24 10:52:06.248  3239  3239 W System.err: StackTrace:
07-24 10:52:06.248  3239  3239 W System.err: java.lang.RuntimeException: com.tns.NativeScriptException: Calling js method onStartJob failed
07-24 10:52:06.248  3239  3239 W System.err: Error: java.lang.NoSuchFieldError: no "I" field "IMPORTANCE_LOW" in class "Landroid/app/NotificationManager;" or its superclasses
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.notifications.MyJobService.onStartJob(MyJobService.java:21)
07-24 10:52:06.248  3239  3239 W System.err:     android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
07-24 10:52:06.248  3239  3239 W System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
07-24 10:52:06.248  3239  3239 W System.err:     android.os.Looper.loop(Looper.java:148)
07-24 10:52:06.248  3239  3239 W System.err:     android.app.ActivityThread.main(ActivityThread.java:5417)
07-24 10:52:06.248  3239  3239 W System.err:     java.lang.reflect.Method.invoke(Native Method)
07-24 10:52:06.248  3239  3239 W System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-24 10:52:06.248  3239  3239 W System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-24 10:52:06.248  3239  3239 W System.err:    at android.app.job.JobService$JobHandler.handleMessage(JobService.java:130)
07-24 10:52:06.248  3239  3239 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
07-24 10:52:06.248  3239  3239 W System.err:    at android.os.Looper.loop(Looper.java:148)
07-24 10:52:06.248  3239  3239 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5417)
07-24 10:52:06.248  3239  3239 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-24 10:52:06.248  3239  3239 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-24 10:52:06.248  3239  3239 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-24 10:52:06.248  3239  3239 W System.err: Caused by: com.tns.NativeScriptException: Calling js method onStartJob failed
07-24 10:52:06.248  3239  3239 W System.err: Error: java.lang.NoSuchFieldError: no "I" field "IMPORTANCE_LOW" in class "Landroid/app/NotificationManager;" or its superclasses
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
07-24 10:52:06.248  3239  3239 W System.err:     com.tns.notifications.MyJobService.onStartJob(MyJobService.java:21)
07-24 10:52:06.248  3239  3239 W System.err:     android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
07-24 10:52:06.248  3239  3239 W System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
07-24 10:52:06.248  3239  3239 W System.err:     android.os.Looper.loop(Looper.java:148)
07-24 10:52:06.248  3239  3239 W System.err:     android.app.ActivityThread.main(ActivityThread.java:5417)
07-24 10:52:06.248  3239  3239 W System.err:     java.lang.reflect.Method.invoke(Native Method)
07-24 10:52:06.248  3239  3239 W System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-24 10:52:06.248  3239  3239 W System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-24 10:52:06.248  3239  3239 W System.err:    at com.tns.Runtime.callJSMethodNative(Native Method)
07-24 10:52:06.248  3239  3239 W System.err:    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
07-24 10:52:06.248  3239  3239 W System.err:    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
07-24 10:52:06.248  3239  3239 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:1109)
07-24 10:52:06.248  3239  3239 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:1089)
07-24 10:52:06.248  3239  3239 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:1081)
07-24 10:52:06.248  3239  3239 W System.err:    at com.tns.notifications.MyJobService.onStartJob(MyJobService.java:21)
07-24 10:52:06.248  3239  3239 W System.err:    at android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
07-24 10:52:06.248  3239  3239 W System.err:    ... 6 more
07-24 10:52:06.248  3239  3239 W System.err: Caused by: java.lang.NoSuchFieldError: no "I" field "IMPORTANCE_LOW" in class "Landroid/app/NotificationManager;" or its superclasses
07-24 10:52:06.248  3239  3239 W System.err:    ... 14 more
--------- beginning of system
07-24 10:52:06.268  1568  1699 I ActivityManager: START u0 {flg=0x14008000 cmp=org.nativescript.bgservice/com.tns.ErrorReportActivity (has extras)} from uid 10058 on display 0
07-24 10:52:06.271  1229  2144 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 331776
07-24 10:52:06.272  1568  1699 D         : HostConnection::get() New Host Connection established 0x9c97c080, tid 1699
07-24 10:52:06.284  3239  3239 I Process : Sending signal. PID: 3239 SIG: 9
07-24 10:52:06.289  1568  1604 W InputDispatcher: channel '43797aa org.nativescript.bgservice/com.tns.NativeScriptActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-24 10:52:06.289  1568  1604 E InputDispatcher: channel '43797aa org.nativescript.bgservice/com.tns.NativeScriptActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-24 10:52:06.291  1568  1977 D GraphicsStats: Buffer count: 3
07-24 10:52:06.305  1568  1580 I WindowState: WIN DEATH: Window{43797aa u0 org.nativescript.bgservice/com.tns.NativeScriptActivity}
07-24 10:52:06.305  1568  1580 W InputDispatcher: Attempted to unregister already unregistered input channel '43797aa org.nativescript.bgservice/com.tns.NativeScriptActivity (server)'
07-24 10:52:06.306  1229  1607 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1536000
07-24 10:52:06.315  1568  1697 I ActivityManager: Process org.nativescript.bgservice (pid 3239) has died
07-24 10:52:06.315  1568  1697 W ActivityManager: Scheduling restart of crashed service org.nativescript.bgservice/com.tns.notifications.MyJobService in 1000ms
07-24 10:52:06.318  3263  3263 I art     : Not late-enabling -Xcheck:jni (already on)
07-24 10:52:06.327  1568  1697 I ActivityManager: Start proc 3263:org.nativescript.bgservice/u0a58 for activity org.nativescript.bgservice/com.tns.ErrorReportActivity
07-24 10:52:06.337  3263  3263 I TNS.Runtime: NativeScript Runtime Version 6.0.0, commit c7133fd2134846a43ca8211df21084845621edf8
07-24 10:52:06.364  3263  3263 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
07-24 10:52:06.380  3263  3263 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
07-24 10:52:06.380  3263  3263 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
07-24 10:52:06.391  1229  1334 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
07-24 10:52:06.392  3263  3283 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-24 10:52:06.394  3263  3263 D         : HostConnection::get() New Host Connection established 0xa1fcf2c0, tid 3263
07-24 10:52:06.428  3263  3283 D         : HostConnection::get() New Host Connection established 0xb3fdb400, tid 3283
07-24 10:52:06.429  3263  3283 I OpenGLRenderer: Initialized EGL, version 1.4
07-24 10:52:06.429  3263  3283 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
07-24 10:52:06.430  3263  3283 D EGL_emulation: eglCreateContext: 0xb0b0b520: maj 3 min 0 rcv 3
07-24 10:52:06.431  3263  3283 D EGL_emulation: eglMakeCurrent: 0xb0b0b520: ver 3 0 (tinfo 0xab635600)
07-24 10:52:06.432  3263  3283 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
07-24 10:52:06.432  3263  3283 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
07-24 10:52:06.435  3263  3283 D EGL_emulation: eglMakeCurrent: 0xb0b0b520: ver 3 0 (tinfo 0xab635600)
07-24 10:52:06.482  1568  1587 I ActivityManager: Displayed org.nativescript.bgservice/com.tns.ErrorReportActivity: +167ms
07-24 10:52:06.482  1568  1579 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 3239 uid 10058
07-24 10:52:07.036  1568  1587 W WindowAnimator: Failed to dispatch window animation state change.
07-24 10:52:07.036  1568  1587 W WindowAnimator: android.os.DeadObjectException
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.os.BinderProxy.transactNative(Native Method)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.os.BinderProxy.transact(Binder.java:503)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.view.Choreographer.doFrame(Choreographer.java:603)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.os.Handler.handleCallback(Handler.java:739)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.os.Handler.dispatchMessage(Handler.java:95)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.os.Looper.loop(Looper.java:148)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at android.os.HandlerThread.run(HandlerThread.java:61)
07-24 10:52:07.036  1568  1587 W WindowAnimator:        at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-24 10:52:09.198  1269  1628 W audio_hw_generic: Not supplying enough data to HAL, expected position 1665237 , only wrote 1528232
^C

**Comment by vhristov5555** [comment]
Resolved with 6.0 release
