### ISSUE TITLE
Calling ng component method from receive broadcaster

### ISSUE THREAD

**Issue by snekbaev** [NativeScript/sample-android-background-services#5]
Hi,

trying to find a solution to the following: I'm able to receive the incoming sms and then broadcast it further for processing. In home component in ```ngOnInit``` I have ```app.android.registerBroadcastReceiver``` registration which successfully receives the sent intent. So far so good. Now I would like to call some other method on the home component, say to update the UI. Question is how to do so?

I've seen native android related solutions regarding broadcast receivers, one is to basically pass the current activity (probably ```this``` which is ng component in case of NS) to newly created broadcast receiver class and use that reference in ```onReceive```, however in NS broadcast class is created inside the ```app.android.registerBroadcastReceiver``` call:
```
var registerFunc = function (context) {
            var receiver = new BroadcastReceiverClass(onReceiveCallback); 
....
```

And a logical follow-up, just to confirm, is that the correct way to unbind in the component:
```
ngOnDestroy() {
        app.android.unregisterBroadcastReceiver(this.appConfig.incomingSmsIntent);
    }
```

Thank you!

**Comment by petekanev** [comment]
@snekbaev I am not sure I understand the problem completely. What exactly is not working on your end, what have you tried so far?

**Comment by snekbaev** [comment]
Hi,

I tried to get the reference to the host NG component, I had:

```
export class HomeComponent implements OnInit, OnDestroy {
    private that : HomeComponent = this;
```

and then tried to use the ```that``` inside onReceive callback. TS complained that it can't find the ```that```. Tried having a global variable and initialize it in the constructor. Apparently what I missed is to try declaring the ```that``` variable inside a function:
```
ngOnInit() {
        const that = this; // <-- this is it

        app.android.registerBroadcastReceiver(this.appConfig.incomingSmsIntent, function onReceiveCallback(context : android.content.Context, intent:  android.content.Intent) {
// that. now works
```
many thanks to @NickIliev who pointed to the example that helped out. Because I was wandering around other similar battery status snippets that only used console log:
https://github.com/NativeScript/NativeScript/issues/473
https://github.com/NativeScript/NativeScript/blob/master/tests/app/application-tests.android.ts
etc.

Thank you!

**Comment by priyangamani** [comment]
Hi,
      @snekbaev  
onReceive function is not working for me....(SMS NOtification using broadcastreceiver)

Code:
android.content.BroadcastReceiver.extend("com.broadcastreceivers.IncomingSmsBroadcastReceiver", {
    onReceive: function(context,intent) {
        console.log("context",context);
        console.log("broad",com.broadcastreceivers.IncomingSmsBroadcastReceiver);
        var messages=  intent.getSerializableExtra("pdus");
        var format=intent.getStringExtra("format");
        console.log("smsmanage",messages);
         console.log("smsmanagerformat",format);
         for(i = 0; i < messages.length; i++) {
            var message = android.telephony.SmsMessage.createFromPdu(messages[i], format);
            var currentMessage= android.telephony.SmsMessage.createFromPdu(messages[i]);
           	var phoneNumber = currentMessage.getDisplayOriginatingAddress();
        console.log("SmsReceiver", "senderNum: "+ message.getDisplayOriginatingAddress() + "; message: " + message.getMessageBody());
        }
    }
});

Maniefest
<receiver android:name="com.broadcastreceivers.IncomingSmsBroadcastReceiver">
    <intent-filter>
        <action android:name="android.provider.Telephony.SMS_RECEIVED" />
        </intent-filter>
</receiver>

**Comment by snekbaev** [comment]
@priyangamani it was a test and the only NS project I've implemented so far. At the moment I have no recollection how I resolved it
