### ISSUE TITLE
BroadcastReceiver JS and TS versions

### ISSUE THREAD

**Issue by snekbaev** [NativeScript/sample-android-background-services#6]
Hi,

based on our discussion in here: https://github.com/NativeScript/android-runtime/issues/635

Just wanted to confirm whether implementation is good enough (it works though):
broadcast receiver is registered in the AndroidManifest
```
<receiver android:name="com.xxxxx.beeper.broadcastreceivers.IncomingSmsBroadcastReceiver">
    <intent-filter android:priority="999">
        <action android:name="android.provider.Telephony.SMS_RECEIVED" />
        </intent-filter>
</receiver>
```

Initial JS version:
```
declare var android: any;
import { AppConfig } from '../app.config';

android.content.BroadcastReceiver.extend("com.xxxxx.beeper.broadcastreceivers.IncomingSmsBroadcastReceiver", {
    
    // init: function() {
    //   console.log("in ctor");
    // },
    onReceive: function(context, intent) {
        //var helper = require("../service-helper");
        //const utils = require("utils/utils");
        //helper.setupAlarm(utils.ad.getApplicationContext());
         
        if (intent.getAction() !== "android.provider.Telephony.SMS_RECEIVED") {
            return;
        }

        let messages: Object[];
        
        try { 
            messages = intent.getSerializableExtra("pdus");
        }
        catch(e) {
            //log
            return;
        }

        const format: string = intent.getStringExtra("format");

        //: android.telephony.SmsMessage[]
        //let smsMessages = [];//android.telephony.SmsMessage.Intents.getMessagesFromIntent(intent);

        for(let i = 0; i < messages.length; i++) {
            const message = android.telephony.SmsMessage.createFromPdu(messages[i], format);
            
            if(message.getDisplayOriginatingAddress() === AppConfig.boxPhoneNumber) {
                const intent = new android.content.Intent(AppConfig.incomingSmsIntent);
                intent.putExtra("message", message.getMessageBody())
                context.getApplicationContext().sendBroadcast(intent);
            }

            // console.log("SmsReceiver", "senderNum: "+ message.getDisplayOriginatingAddress() + "; message: " + message.getMessageBody());
        }
    }
});
```

Current TS version:

```
module com {
  module xxxxx {
      module beeper {
        module broadcastreceivers {
            //@JavaProxy("IncomingSmsBroadcastReceiver")
            @JavaProxy("com.xxxxx.beeper.broadcastreceivers.IncomingSmsBroadcastReceiver")
            class IncomingSmsBroadcastReceiver extends android.content.BroadcastReceiver {
                public onReceive(context : android.content.Context, intent: android.content.Intent) {
                
                    //const utils = require("utils/utils");
                    //helper.setupAlarm(utils.ad.getApplicationContext());
                    
                    if (intent.getAction() !== "android.provider.Telephony.SMS_RECEIVED") {
                        return;
                    }

                    let messages: Object[];
                    
                    try { 
                        messages = <any>intent.getSerializableExtra("pdus");
                    }
                    catch(e) {
                        //log
                        return;
                    }

                    const format: string = intent.getStringExtra("format");

                    //android.telephony.SmsMessage[]
                    //let smsMessages = [];//android.telephony.SmsMessage.Intents.getMessagesFromIntent(intent);

                    for(let i = 0; i < messages.length; i++) {
                        const message = android.telephony.SmsMessage.createFromPdu(messages[i], format);
                        
                        if(message.getDisplayOriginatingAddress() === AppConfig.boxPhoneNumber) {
                            const intent = new android.content.Intent(AppConfig.incomingSmsIntent);
                            intent.putExtra("message", message.getMessageBody())
                            context.getApplicationContext().sendBroadcast(intent);
                        }

                        // console.log("SmsReceiver", "senderNum: "+ message.getDisplayOriginatingAddress() + "; message: " + message.getMessageBody());
                    }
                }
            }
        }
    }
  }
}
```
TS version can be made better. If I have the ```declare module``` and that class in d.ts file then it complains that it can't find the ```android``` and ```@JavaProxy```. Need to figure out how to make the TS happy :)

Any suggestions are welcome.

**Comment by armackey** [comment]
Hey, I'm trying to implement this code and it's not working. When I receive a message, nothing logs to the console. Is there something I'm missing?

**Comment by thiagoufg** [comment]
Please, would you give me more info about this code?

I'm using Nativescript Angular version 2.5.4 and I cannot make it work.

I don't want to read the inbox of SMSs (there are plugins capable of doing that). What I want is to intercept new incoming SMSs. This seems to be the closest code to what I want.

Do you have a github repository with the complete source code?

I don't know where to put that file, so the namespaces "Android" and "AppConfig" will be recognized by the typescript compiler, or how the AndroidManifest will "find" the implementation of the IncomingSmsBroadcastReceiver class.

Here's what I did.

I have created a new Nativescript Angular project.
Then, I've put a file called a.ts in the root of the app/ folder, with the contents showed it the "current TS version", above.
Also, I've editted the AndroidManifest with the receiver tags that you showed.

Then I run:
nativescript run android

And these are the errors I get:

> app/modules/sms/a.ts(9,56): error TS2507: Type 'any' is not a constructor function type.
> 
> app/modules/sms/a.ts(10,44): error TS2503: Cannot find namespace 'android'.
> 
> app/modules/sms/a.ts(10,77): error TS2503: Cannot find namespace 'android'.
> 
> app/modules/sms/a.ts(37,71): error TS2304: Cannot find name 'AppConfig'.
> 
> app/modules/sms/a.ts(38,71): error TS2304: Cannot find name 'AppConfig'.
> 
> TypeScript compiler failed with exit code 1
> Sending exception report (press Ctrl+C to stop).....

Please, help!

Thanks...

**Comment by petekanev** [comment]
@thiagoufg it would appear that the TypeScript compiler is complaining because it doesn't have the android SDK typings. Comment out the typescript code and do a `tns build android --androidTypings` to have definitions generations for you. Also, I do not provide support for any code outside of the sample, so that kind of questions should be directed to the nativescript forums. 
Thank you.

**Comment by priyangamani** [comment]
I'm also trying to implement this code and on receive function  it's not working.
