### ISSUE TITLE
Crashes when attempting to run on Android reboot

### ISSUE THREAD

**Issue by AnthonySmith01** [NativeScript/sample-android-background-services#9]
Hi

Great project, thanks for sharing.
I noticed on my Android device that the service crashes after a reboot. Here is the error (any ideas?):

java.lang.RuntimeException: Unable to instantiate receiver com.tns.broadcastreceivers.NotificationServiceStarterReceiver: java.lang.ClassNotFoundException: Didn't find class "com.tns.broadcastreceivers.NotificationServiceStarterReceiver" on path: DexPathList[[zip file "/data/app/org.nativescript.bgservice-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.bgservice-1/lib/arm64, /data/app/org.nativescript.bgservice-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3021)
	at android.app.ActivityThread.-wrap18(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.broadcastreceivers.NotificationServiceStarterReceiver" on path: DexPathList[[zip file "/data/app/org.nativescript.bgservice-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.bgservice-1/lib/arm64, /data/app/org.nativescript.bgservice-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3016)
	... 8 more

**Comment by AnthonySmith01** [comment]
It looks like a corresponding java file is missing from the project in:
sample-android-background-services/platforms/android/src/main/assets/app/broadcastreceivers/

I'll take a look and get back to this issue if I work it out.... but for now, it's Christmas!

**Comment by snekbaev** [comment]
@sm1ddy this might not be related specifically to your case, but I was encountering that problem from time to time at runtime when NS wasn't able to find the broadcaster class. The fix I applied was to remove the android platform and add it again. Then do the build, deploy and see if it works. After that it is ok to continue with livesync approach until the next time it occurs. Hope this helps.

P.S.: had that with 2.4.0

**Comment by AnthonySmith01** [comment]
Thanks mate, the advice is much appreciated. :)

I actually just fixed my issue by manually creating this file:
sample-android-background-services/platforms/android/src/main/java/com/tns/broadcastreceivers/NotificationServiceStarter.java 

(It's missing from the project).

I added the following code to the file:

> package com.tns.broadcastreceivers;
> 
> @com.tns.JavaScriptImplementation(javaScriptFile = "./broadcastreceivers/NotificationServiceStarterReceiver.js")
> public class NotificationServiceStarterReceiver extends android.support.v4.content.WakefulBroadcastReceiver implements com.tns.NativeScriptHashCodeProvider {
> 	public NotificationServiceStarterReceiver(){
> 		super();
> 		com.tns.Runtime.initInstance(this);
> 	}
> 
> 	public void onReceive(android.content.Context param_0, android.content.Intent param_1)  {
> 		java.lang.Object[] args = new java.lang.Object[2];
> 		args[0] = param_0;
> 		args[1] = param_1;
> 		com.tns.Runtime.callJSMethod(this, "onReceive", void.class, args);
> 	}
> 
> 	public boolean equals__super(java.lang.Object other) {
> 		return super.equals(other);
> 	}
> 
> 	public int hashCode__super() {
> 		return super.hashCode();
> 	}
> 
> }
> 

I'll leave this issue open for now in case the project owner @Pip3r4o wants to take a look.

**Comment by snekbaev** [comment]
@sm1ddy imho, that's not a good approach. The moment you will need to re-add the android platform it will be wiped, moreover a lot of stuff there is being generated. Re-adding might be required when, for example you will be working on a NS custom plugin and, say, update its packages, there were also several other cases, can't recall all. But in the most of situations if some weirdness is happening re-adding the specific platform usually helps.

So be warned :)

**Comment by AnthonySmith01** [comment]
Generally that is a good point.

This project is different, however, because it relies on @Pip3r4o's android-manifest and java class additions to the platforms folder which facilitates a native background service. Even without my changes, it will still break if you remove the Android platform.

So yep you're right but this is a special case even without my changes (unless I'm wrong of course). :)

The NotificationServiceStarter.java isn't in the main github project so it should probably be added in, not sure if others have encountered this issue (but I would be surprised if they didn't).

**Comment by petekanev** [comment]
Hey, I'd like to pitch in by saying that the class should be present after
a complete build, as it is generated by the binding generator (called to
during build phase) in the form of a compiled class (.class packed in a
.dex) in build/intermediates.
Please describe the steps from a clean slate to the aforementioned crash,
so we can pinpoint the issue.

Thanks and happy holidays!

**Comment by simonettoa** [comment]
I have the same errors of  @sm1ddy . The application is crashing and the report is this below:

`java.lang.RuntimeException: Unable to instantiate service com.tns.notifications.NotificationIntentService: java.lang.InstantiationException: java.lang.Class<com.tns.notifications.NotificationIntentService> has no zero argument constructor
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2862)
	at android.app.ActivityThread.-wrap4(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.InstantiationException: java.lang.Class<com.tns.notifications.NotificationIntentService> has no zero argument constructor
	at java.lang.Class.newInstance(Native Method)
	at android.app.Activi`

I also tried to add the file as @sm1ddy wrote and run again but nothing is changed.
What I've done:
- cloned the project
- tns install
- tns run android

It starts, I click the button and put the app in background, after a while the popup message of error appears ('Unfortunately, backgroundservicedroid has stopped').

**Comment by petekanev** [comment]
@simonettoa this is a known limitation (both of android and the nativescript android tooling), and unfortunately one that we haven't had the time to address for some time now. 

Until this is fixed you can provide your own implementation of IntentService with an empty default constructor, and then expose it to JavaScript so that you can implement the NotificationIntentService. 

I might be able to expose a simple plugin this weekend that will alleviate the issue. Making no promises.

**Comment by simonettoa** [comment]
@Pip3r4o thanks, I will try.

**Comment by petekanev** [comment]
Sample project was cleaned up and updated. I also exposed IntentService with no constructor, and there should be no problems getting a notification after a period of time when pressing the button.
